
## static_countries

UPDATE static_countries SET cn_short_da='Andorra' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_da='Forenede Arabiske Emirater' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_da='Afghanistan' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_da='Antigua og Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_da='Anguilla' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_da='Albanien' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_da='Armenien' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_da='Hollandske Antiller' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_da='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_da='Antarktis' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_da='Argentina' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_da='Amerikansk Samoa' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_da='Østrig' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_da='Australien' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_da='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_da='Aserbajdsjan' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_da='Bosnien-Hercegovina' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_da='Barbados' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_da='Bangladesh' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_da='Belgien' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_da='Burkina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_da='Bulgarien' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_da='Bahrain' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_da='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_da='Benin' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_da='Bermuda' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_da='Brunei Darussalam' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_da='Bolivia' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_da='Brasilien' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_da='Bahamas' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_da='Bhutan' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_da='Bouvetø' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_da='Botswana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_da='Hviderusland' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_da='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_da='Canada' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_da='Cocos-øerne (Keelingøerne)' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_da='Den Demokratiske Republik Congo' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_da='Centralafrikanske Republik' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_da='Congo' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_da='Schweiz' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_da='Elfenbenskysten' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_da='Cook-øerne' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_da='Chile' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_da='Cameroun' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_da='Kina' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_da='Colombia' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_da='Costa Rica' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_da='Cuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_da='Kap Verde' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_da='Juleøen' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_da='Cypern' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_da='Tjekkiet' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_da='Tyskland' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_da='Djibouti' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_da='Danmark' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_da='Dominica' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_da='Den Dominikanske Republik' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_da='Algeriet' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_da='Ecuador' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_da='Estland' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_da='Egypten' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_da='Vestsahara' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_da='Eritrea' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_da='Spanien' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_da='Etiopien' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_da='Finland' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_da='Fiji-øerne' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_da='Falklandsøerne' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_da='Mikronesiens Forenede Stater' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_da='Færøerne' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_da='Frankrig' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_da='Gabon' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_da='Det Forenede Kongerige' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_da='Grenada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_da='Georgien' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_da='Fransk Guyana' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_da='Ghana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_da='Gibraltar' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_da='Grønland' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_da='Gambia' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_da='Guinea' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_da='Guadeloupe' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_da='Ækvatorialguinea' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_da='Grækenland' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_da='South Georgia og De Sydlige Sandwichøer' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_da='Guatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_da='Guam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_da='Guinea-Bissau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_da='Guyana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_da='SAR Hongkong' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_da='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_da='Kroatien' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_da='Haiti' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_da='Ungarn' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_da='Indonesien' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_da='Irland' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_da='Israel' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_da='Indien' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_da='Det Britiske Territorium i Det Indiske Ocean' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_da='Irak' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_da='Iran' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_da='Island' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_da='Italien' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_da='Jamaica' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_da='Jordan' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_da='Japan' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_da='Kenya' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_da='Kirgisistan' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_da='Cambodja' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_da='Kiribati' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_da='Comorerne' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_da='Saint Kitts og Nevis' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_da='Nordkorea' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_da='Sydkorea' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_da='Kuwait' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_da='Caymanøerne' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_da='Kasakhstan' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_da='Laos' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_da='Libanon' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_da='Saint Lucia' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_da='Liechtenstein' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_da='Sri Lanka' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_da='Liberia' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_da='Lesotho' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_da='Litauen' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_da='Luxembourg' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_da='Letland' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_da='Libyen' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_da='Marokko' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_da='Monaco' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_da='Republikken Moldova' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_da='Madagaskar' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_da='Marshalløerne' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_da='Republikken Makedonien' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_da='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_da='Myanmar' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_da='Mongoliet' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_da='SAR Macao' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_da='Nordmarianerne' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_da='Martinique' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_da='Mauretanien' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_da='Montserrat' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_da='Malta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_da='Mauritius' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_da='Maldiverne' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_da='Malawi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_da='Mexico' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_da='Malaysia' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_da='Mozambique' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_da='Namibia' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_da='Ny Caledonien' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_da='Niger' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_da='Norfolk Island' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_da='Nigeria' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_da='Nicaragua' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_da='Nederlandene' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_da='Norge' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_da='Nepal' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_da='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_da='Niue' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_da='New Zealand' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_da='Oman' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_da='Panama' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_da='Peru' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_da='Fransk Polynesien' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_da='Papua Ny Guinea' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_da='Filippinerne' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_da='Pakistan' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_da='Polen' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_da='Saint Pierre og Miquelon' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_da='Pitcairn' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_da='Puerto Rico' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_da='Portugal' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_da='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_da='Paraguay' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_da='Qatar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_da='Reunion' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_da='Rumænien' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_da='Rusland' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_da='Rwanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_da='Saudi-Arabien' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_da='Salomonøerne' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_da='Seychellerne' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_da='Sudan' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_da='Sverige' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_da='Singapore' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_da='St. Helena' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_da='Slovenien' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_da='Svalbard og Jan Mayen' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_da='Slovakiet' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_da='Sierra Leone' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_da='San Marino' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_da='Senegal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_da='Somalia' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_da='Surinam' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_da='São Tomé og Príncipe' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_da='El Salvador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_da='Syrien' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_da='Swaziland' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_da='Turks- og Caicosøerne' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_da='Tchad' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_da='Franske Besiddelser i Det Sydlige Indiske Ocean' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_da='Togo' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_da='Thailand' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_da='Tadsjikistan' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_da='Tokelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_da='Turkmenistan' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_da='Tunesien' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_da='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_da='Timor-Leste' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_da='Tyrkiet' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_da='Trinidad og Tobago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_da='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_da='Taiwan' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_da='Tanzania' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_da='Ukraine' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_da='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_da='De Mindre Amerikanske Oversøiske Øer' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_da='USA' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_da='Uruguay' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_da='Usbekistan' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_da='Vatikanstaten' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_da='St. Vincent og Grenadinerne' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_da='Venezuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_da='De britiske jomfruøer' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_da='De amerikanske jomfruøer' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_da='Vietnam' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_da='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_da='Wallis og Futunaøerne' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_da='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_da='Yemen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_da='Mayotte' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_da='Sydafrika' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_da='Zambia' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_da='Zimbabwe' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_da='De palæstinensiske områder' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_da='Serbien og Montenegro' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_da='' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_da='Heard- og McDonald-øerne' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_da='' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_da='' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_da='' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_da='' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_da='' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_da='' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_da='' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_da='' WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_short_da='' WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_short_da='' WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_short_da='' WHERE cn_iso_2='SS';

## static_currencies

UPDATE static_currencies SET cu_name_da='Dirham fra de Forenede Arabiske Emirater',cu_sub_name_da='' WHERE cu_iso_3='AED';
UPDATE static_currencies SET cu_name_da='Albansk lek',cu_sub_name_da='' WHERE cu_iso_3='ALL';
UPDATE static_currencies SET cu_name_da='Armensk dram',cu_sub_name_da='' WHERE cu_iso_3='AMD';
UPDATE static_currencies SET cu_name_da='Gylden fra De Nederlandske Antiller',cu_sub_name_da='' WHERE cu_iso_3='ANG';
UPDATE static_currencies SET cu_name_da='Angolansk kwanza',cu_sub_name_da='' WHERE cu_iso_3='AOA';
UPDATE static_currencies SET cu_name_da='Argentinsk peso',cu_sub_name_da='' WHERE cu_iso_3='ARS';
UPDATE static_currencies SET cu_name_da='Australsk dollar',cu_sub_name_da='' WHERE cu_iso_3='AUD';
UPDATE static_currencies SET cu_name_da='Arubansk gylden',cu_sub_name_da='' WHERE cu_iso_3='AWG';
UPDATE static_currencies SET cu_name_da='',cu_sub_name_da='' WHERE cu_iso_3='AZN';
UPDATE static_currencies SET cu_name_da='Bosnien-Hercegovinsk konvertibel mark',cu_sub_name_da='' WHERE cu_iso_3='BAM';
UPDATE static_currencies SET cu_name_da='Barbadisk dollar',cu_sub_name_da='' WHERE cu_iso_3='BBD';
UPDATE static_currencies SET cu_name_da='Bangladeshisk taka',cu_sub_name_da='' WHERE cu_iso_3='BDT';
UPDATE static_currencies SET cu_name_da='Ny Bulgarsk lev',cu_sub_name_da='' WHERE cu_iso_3='BGN';
UPDATE static_currencies SET cu_name_da='Bahrainsk dinar',cu_sub_name_da='' WHERE cu_iso_3='BHD';
UPDATE static_currencies SET cu_name_da='Burundisk franc',cu_sub_name_da='' WHERE cu_iso_3='BIF';
UPDATE static_currencies SET cu_name_da='Bermudansk dollar',cu_sub_name_da='' WHERE cu_iso_3='BMD';
UPDATE static_currencies SET cu_name_da='Bruneisk dollar',cu_sub_name_da='' WHERE cu_iso_3='BND';
UPDATE static_currencies SET cu_name_da='',cu_sub_name_da='' WHERE cu_iso_3='BOB';
UPDATE static_currencies SET cu_name_da='Brasiliansk real',cu_sub_name_da='' WHERE cu_iso_3='BRL';
UPDATE static_currencies SET cu_name_da='Bahamansk dollar',cu_sub_name_da='' WHERE cu_iso_3='BSD';
UPDATE static_currencies SET cu_name_da='Bhutansk ngultrum',cu_sub_name_da='' WHERE cu_iso_3='BTN';
UPDATE static_currencies SET cu_name_da='Botswansk pula',cu_sub_name_da='' WHERE cu_iso_3='BWP';
UPDATE static_currencies SET cu_name_da='Hviderussisk rubel',cu_sub_name_da='' WHERE cu_iso_3='BYR';
UPDATE static_currencies SET cu_name_da='Belizisk dollar',cu_sub_name_da='' WHERE cu_iso_3='BZD';
UPDATE static_currencies SET cu_name_da='Canadisk dollar',cu_sub_name_da='' WHERE cu_iso_3='CAD';
UPDATE static_currencies SET cu_name_da='Congolesisk franc congolais',cu_sub_name_da='' WHERE cu_iso_3='CDF';
UPDATE static_currencies SET cu_name_da='Schweizisk franc',cu_sub_name_da='' WHERE cu_iso_3='CHF';
UPDATE static_currencies SET cu_name_da='Chilensk peso',cu_sub_name_da='' WHERE cu_iso_3='CLP';
UPDATE static_currencies SET cu_name_da='Kinesisk yuan renminbi',cu_sub_name_da='' WHERE cu_iso_3='CNY';
UPDATE static_currencies SET cu_name_da='Colombiansk peso',cu_sub_name_da='' WHERE cu_iso_3='COP';
UPDATE static_currencies SET cu_name_da='Costaricansk colon',cu_sub_name_da='' WHERE cu_iso_3='CRC';
UPDATE static_currencies SET cu_name_da='Cubansk peso',cu_sub_name_da='' WHERE cu_iso_3='CUP';
UPDATE static_currencies SET cu_name_da='Kapverdisk escudo',cu_sub_name_da='' WHERE cu_iso_3='CVE';
UPDATE static_currencies SET cu_name_da='Cypriotisk pund',cu_sub_name_da='' WHERE cu_iso_3='CYP';
UPDATE static_currencies SET cu_name_da='Tjekkisk koruna',cu_sub_name_da='' WHERE cu_iso_3='CZK';
UPDATE static_currencies SET cu_name_da='Djiboutisk franc',cu_sub_name_da='' WHERE cu_iso_3='DJF';
UPDATE static_currencies SET cu_name_da='Dansk krone',cu_sub_name_da='' WHERE cu_iso_3='DKK';
UPDATE static_currencies SET cu_name_da='Dominikansk peso',cu_sub_name_da='' WHERE cu_iso_3='DOP';
UPDATE static_currencies SET cu_name_da='Algerisk dinar',cu_sub_name_da='' WHERE cu_iso_3='DZD';
UPDATE static_currencies SET cu_name_da='Estisk kroon',cu_sub_name_da='' WHERE cu_iso_3='EEK';
UPDATE static_currencies SET cu_name_da='Egyptisk pund',cu_sub_name_da='' WHERE cu_iso_3='EGP';
UPDATE static_currencies SET cu_name_da='Eritreisk nakfa',cu_sub_name_da='' WHERE cu_iso_3='ERN';
UPDATE static_currencies SET cu_name_da='Etiopisk birr',cu_sub_name_da='' WHERE cu_iso_3='ETB';
UPDATE static_currencies SET cu_name_da='Euro',cu_sub_name_da='' WHERE cu_iso_3='EUR';
UPDATE static_currencies SET cu_name_da='Fijiansk dollar',cu_sub_name_da='' WHERE cu_iso_3='FJD';
UPDATE static_currencies SET cu_name_da='Pund fra Falklandsøerne',cu_sub_name_da='' WHERE cu_iso_3='FKP';
UPDATE static_currencies SET cu_name_da='Britisk pund',cu_sub_name_da='' WHERE cu_iso_3='GBP';
UPDATE static_currencies SET cu_name_da='Georgisk lari',cu_sub_name_da='' WHERE cu_iso_3='GEL';
UPDATE static_currencies SET cu_name_da='Ghanesisk cedi',cu_sub_name_da='' WHERE cu_iso_3='GHC';
UPDATE static_currencies SET cu_name_da='Gibraltarisk pund',cu_sub_name_da='' WHERE cu_iso_3='GIP';
UPDATE static_currencies SET cu_name_da='Gambisk dalasi',cu_sub_name_da='' WHERE cu_iso_3='GMD';
UPDATE static_currencies SET cu_name_da='Guineansk franc',cu_sub_name_da='' WHERE cu_iso_3='GNF';
UPDATE static_currencies SET cu_name_da='Guatemalansk quetzal',cu_sub_name_da='' WHERE cu_iso_3='GTQ';
UPDATE static_currencies SET cu_name_da='Guineansk peso',cu_sub_name_da='' WHERE cu_iso_3='GWP';
UPDATE static_currencies SET cu_name_da='Guyansk dollar',cu_sub_name_da='' WHERE cu_iso_3='GYD';
UPDATE static_currencies SET cu_name_da='',cu_sub_name_da='' WHERE cu_iso_3='HKD';
UPDATE static_currencies SET cu_name_da='Honduransk lempira',cu_sub_name_da='' WHERE cu_iso_3='HNL';
UPDATE static_currencies SET cu_name_da='Kroatisk kuna',cu_sub_name_da='' WHERE cu_iso_3='HRK';
UPDATE static_currencies SET cu_name_da='Haitisk gourde',cu_sub_name_da='' WHERE cu_iso_3='HTG';
UPDATE static_currencies SET cu_name_da='Ungarsk forint',cu_sub_name_da='' WHERE cu_iso_3='HUF';
UPDATE static_currencies SET cu_name_da='Indonesisk pupiah',cu_sub_name_da='' WHERE cu_iso_3='IDR';
UPDATE static_currencies SET cu_name_da='Ny israelsk shekel',cu_sub_name_da='' WHERE cu_iso_3='ILS';
UPDATE static_currencies SET cu_name_da='Indisk rupee',cu_sub_name_da='' WHERE cu_iso_3='INR';
UPDATE static_currencies SET cu_name_da='Irakisk dinar',cu_sub_name_da='' WHERE cu_iso_3='IQD';
UPDATE static_currencies SET cu_name_da='Iransk rial',cu_sub_name_da='' WHERE cu_iso_3='IRR';
UPDATE static_currencies SET cu_name_da='Islandsk krona',cu_sub_name_da='' WHERE cu_iso_3='ISK';
UPDATE static_currencies SET cu_name_da='Jamaicansk dollar',cu_sub_name_da='' WHERE cu_iso_3='JMD';
UPDATE static_currencies SET cu_name_da='Jordansk dinar',cu_sub_name_da='' WHERE cu_iso_3='JOD';
UPDATE static_currencies SET cu_name_da='Japansk yen',cu_sub_name_da='' WHERE cu_iso_3='JPY';
UPDATE static_currencies SET cu_name_da='Kenyansk shilling',cu_sub_name_da='' WHERE cu_iso_3='KES';
UPDATE static_currencies SET cu_name_da='Kirgisisk som',cu_sub_name_da='' WHERE cu_iso_3='KGS';
UPDATE static_currencies SET cu_name_da='Cambodjansk riel',cu_sub_name_da='' WHERE cu_iso_3='KHR';
UPDATE static_currencies SET cu_name_da='Comorisk franc',cu_sub_name_da='' WHERE cu_iso_3='KMF';
UPDATE static_currencies SET cu_name_da='Nordkoreansk won',cu_sub_name_da='' WHERE cu_iso_3='KPW';
UPDATE static_currencies SET cu_name_da='Sydkoreansk won',cu_sub_name_da='' WHERE cu_iso_3='KRW';
UPDATE static_currencies SET cu_name_da='Kuwaitisk dinar',cu_sub_name_da='' WHERE cu_iso_3='KWD';
UPDATE static_currencies SET cu_name_da='Dollar fra Caymanøerne',cu_sub_name_da='' WHERE cu_iso_3='KYD';
UPDATE static_currencies SET cu_name_da='Kasakhisk tenge',cu_sub_name_da='' WHERE cu_iso_3='KZT';
UPDATE static_currencies SET cu_name_da='Laotisk kip',cu_sub_name_da='' WHERE cu_iso_3='LAK';
UPDATE static_currencies SET cu_name_da='Libanesisk pund',cu_sub_name_da='' WHERE cu_iso_3='LBP';
UPDATE static_currencies SET cu_name_da='Srilankansk rupee',cu_sub_name_da='' WHERE cu_iso_3='LKR';
UPDATE static_currencies SET cu_name_da='Liberisk dollar',cu_sub_name_da='' WHERE cu_iso_3='LRD';
UPDATE static_currencies SET cu_name_da='Lesothisk loti',cu_sub_name_da='' WHERE cu_iso_3='LSL';
UPDATE static_currencies SET cu_name_da='Litauisk lita',cu_sub_name_da='' WHERE cu_iso_3='LTL';
UPDATE static_currencies SET cu_name_da='Lettisk lats',cu_sub_name_da='' WHERE cu_iso_3='LVL';
UPDATE static_currencies SET cu_name_da='Libysk dinar',cu_sub_name_da='' WHERE cu_iso_3='LYD';
UPDATE static_currencies SET cu_name_da='Marokkansk dirham',cu_sub_name_da='' WHERE cu_iso_3='MAD';
UPDATE static_currencies SET cu_name_da='Moldovisk leu',cu_sub_name_da='' WHERE cu_iso_3='MDL';
UPDATE static_currencies SET cu_name_da='Makedonsk denar',cu_sub_name_da='' WHERE cu_iso_3='MKD';
UPDATE static_currencies SET cu_name_da='Myanmarsk kyat',cu_sub_name_da='' WHERE cu_iso_3='MMK';
UPDATE static_currencies SET cu_name_da='Mongolsk tugrik',cu_sub_name_da='' WHERE cu_iso_3='MNT';
UPDATE static_currencies SET cu_name_da='Macaosk pataca',cu_sub_name_da='' WHERE cu_iso_3='MOP';
UPDATE static_currencies SET cu_name_da='Mauritansk ouguiya',cu_sub_name_da='' WHERE cu_iso_3='MRO';
UPDATE static_currencies SET cu_name_da='Maltesisk lira',cu_sub_name_da='' WHERE cu_iso_3='MTL';
UPDATE static_currencies SET cu_name_da='Mauritisk rupee',cu_sub_name_da='' WHERE cu_iso_3='MUR';
UPDATE static_currencies SET cu_name_da='Maldivisk rufiyaa',cu_sub_name_da='' WHERE cu_iso_3='MVR';
UPDATE static_currencies SET cu_name_da='Malawisk kwacha',cu_sub_name_da='' WHERE cu_iso_3='MWK';
UPDATE static_currencies SET cu_name_da='Mexicansk peso',cu_sub_name_da='' WHERE cu_iso_3='MXN';
UPDATE static_currencies SET cu_name_da='Malaysisk ringgit',cu_sub_name_da='' WHERE cu_iso_3='MYR';
UPDATE static_currencies SET cu_name_da='Mozambiquisk metical',cu_sub_name_da='' WHERE cu_iso_3='MZM';
UPDATE static_currencies SET cu_name_da='Namibisk dollar',cu_sub_name_da='' WHERE cu_iso_3='NAD';
UPDATE static_currencies SET cu_name_da='Nigeriansk naira',cu_sub_name_da='' WHERE cu_iso_3='NGN';
UPDATE static_currencies SET cu_name_da='Nicaraguansk cordoba oro',cu_sub_name_da='' WHERE cu_iso_3='NIO';
UPDATE static_currencies SET cu_name_da='Norsk krone',cu_sub_name_da='' WHERE cu_iso_3='NOK';
UPDATE static_currencies SET cu_name_da='Nepalesisk rupee',cu_sub_name_da='' WHERE cu_iso_3='NPR';
UPDATE static_currencies SET cu_name_da='New Zealandsk dollar',cu_sub_name_da='' WHERE cu_iso_3='NZD';
UPDATE static_currencies SET cu_name_da='Omansk rial',cu_sub_name_da='' WHERE cu_iso_3='OMR';
UPDATE static_currencies SET cu_name_da='Panamansk balboa',cu_sub_name_da='' WHERE cu_iso_3='PAB';
UPDATE static_currencies SET cu_name_da='Peruviansk sol nuevo',cu_sub_name_da='' WHERE cu_iso_3='PEN';
UPDATE static_currencies SET cu_name_da='Papuansk kina',cu_sub_name_da='' WHERE cu_iso_3='PGK';
UPDATE static_currencies SET cu_name_da='Filippinsk peso',cu_sub_name_da='' WHERE cu_iso_3='PHP';
UPDATE static_currencies SET cu_name_da='Pakistansk rupee',cu_sub_name_da='' WHERE cu_iso_3='PKR';
UPDATE static_currencies SET cu_name_da='Polsk zloty',cu_sub_name_da='' WHERE cu_iso_3='PLN';
UPDATE static_currencies SET cu_name_da='Paraguaysk guarani',cu_sub_name_da='' WHERE cu_iso_3='PYG';
UPDATE static_currencies SET cu_name_da='Qatarsk rial',cu_sub_name_da='' WHERE cu_iso_3='QAR';
UPDATE static_currencies SET cu_name_da='Rumænsk leu',cu_sub_name_da='' WHERE cu_iso_3='ROL';
UPDATE static_currencies SET cu_name_da='Russisk rubel',cu_sub_name_da='' WHERE cu_iso_3='RUB';
UPDATE static_currencies SET cu_name_da='Rwandisk franc',cu_sub_name_da='' WHERE cu_iso_3='RWF';
UPDATE static_currencies SET cu_name_da='Saudisk riyal',cu_sub_name_da='' WHERE cu_iso_3='SAR';
UPDATE static_currencies SET cu_name_da='Salomonsk dollar',cu_sub_name_da='' WHERE cu_iso_3='SBD';
UPDATE static_currencies SET cu_name_da='Seychellisk rupee',cu_sub_name_da='' WHERE cu_iso_3='SCR';
UPDATE static_currencies SET cu_name_da='',cu_sub_name_da='' WHERE cu_iso_3='SDG';
UPDATE static_currencies SET cu_name_da='Svensk krona',cu_sub_name_da='' WHERE cu_iso_3='SEK';
UPDATE static_currencies SET cu_name_da='Singaporeansk dollar',cu_sub_name_da='' WHERE cu_iso_3='SGD';
UPDATE static_currencies SET cu_name_da='Pund fra Saint Helena',cu_sub_name_da='' WHERE cu_iso_3='SHP';
UPDATE static_currencies SET cu_name_da='Slovensk tolar',cu_sub_name_da='' WHERE cu_iso_3='SIT';
UPDATE static_currencies SET cu_name_da='Slovakisk koruna',cu_sub_name_da='' WHERE cu_iso_3='SKK';
UPDATE static_currencies SET cu_name_da='Sierraleonsk leone',cu_sub_name_da='' WHERE cu_iso_3='SLL';
UPDATE static_currencies SET cu_name_da='Somalisk shilling',cu_sub_name_da='' WHERE cu_iso_3='SOS';
UPDATE static_currencies SET cu_name_da='Dobra fra Sao Tome og Principe',cu_sub_name_da='' WHERE cu_iso_3='STD';
UPDATE static_currencies SET cu_name_da='Salvadoransk colon',cu_sub_name_da='' WHERE cu_iso_3='SVC';
UPDATE static_currencies SET cu_name_da='Syrisk pund',cu_sub_name_da='' WHERE cu_iso_3='SYP';
UPDATE static_currencies SET cu_name_da='Swazilandsk lilangeni',cu_sub_name_da='' WHERE cu_iso_3='SZL';
UPDATE static_currencies SET cu_name_da='Thailandsk baht',cu_sub_name_da='' WHERE cu_iso_3='THB';
UPDATE static_currencies SET cu_name_da='Tadsjikisk somoni',cu_sub_name_da='' WHERE cu_iso_3='TJS';
UPDATE static_currencies SET cu_name_da='Turkmensk manat',cu_sub_name_da='' WHERE cu_iso_3='TMM';
UPDATE static_currencies SET cu_name_da='Tunesisk dinar',cu_sub_name_da='' WHERE cu_iso_3='TND';
UPDATE static_currencies SET cu_name_da='Tongask paʻanga',cu_sub_name_da='' WHERE cu_iso_3='TOP';
UPDATE static_currencies SET cu_name_da='Dollar fra Trinidad og Tobago',cu_sub_name_da='' WHERE cu_iso_3='TTD';
UPDATE static_currencies SET cu_name_da='Ny taiwansk dollar',cu_sub_name_da='' WHERE cu_iso_3='TWD';
UPDATE static_currencies SET cu_name_da='Tanzanisk shilling',cu_sub_name_da='' WHERE cu_iso_3='TZS';
UPDATE static_currencies SET cu_name_da='Ukrainsk grynia',cu_sub_name_da='' WHERE cu_iso_3='UAH';
UPDATE static_currencies SET cu_name_da='Ugandisk shilling',cu_sub_name_da='' WHERE cu_iso_3='UGX';
UPDATE static_currencies SET cu_name_da='Amerikanske dollar',cu_sub_name_da='' WHERE cu_iso_3='USD';
UPDATE static_currencies SET cu_name_da='Uruguaysk peso uruguayo',cu_sub_name_da='' WHERE cu_iso_3='UYU';
UPDATE static_currencies SET cu_name_da='Usbekisk sum',cu_sub_name_da='' WHERE cu_iso_3='UZS';
UPDATE static_currencies SET cu_name_da='',cu_sub_name_da='' WHERE cu_iso_3='VEF';
UPDATE static_currencies SET cu_name_da='Vietnamesisk dong',cu_sub_name_da='' WHERE cu_iso_3='VND';
UPDATE static_currencies SET cu_name_da='Vanuaisk vatu',cu_sub_name_da='' WHERE cu_iso_3='VUV';
UPDATE static_currencies SET cu_name_da='Samoansk tala',cu_sub_name_da='' WHERE cu_iso_3='WST';
UPDATE static_currencies SET cu_name_da='Beninsk CFA-franc',cu_sub_name_da='' WHERE cu_iso_3='XAF';
UPDATE static_currencies SET cu_name_da='Øst-karaibisk dollar',cu_sub_name_da='' WHERE cu_iso_3='XCD';
UPDATE static_currencies SET cu_name_da='',cu_sub_name_da='' WHERE cu_iso_3='XOF';
UPDATE static_currencies SET cu_name_da='CFP-franc',cu_sub_name_da='' WHERE cu_iso_3='XPF';
UPDATE static_currencies SET cu_name_da='Yemenitisk rial',cu_sub_name_da='' WHERE cu_iso_3='YER';
UPDATE static_currencies SET cu_name_da='Sydafrikansk rand',cu_sub_name_da='' WHERE cu_iso_3='ZAR';
UPDATE static_currencies SET cu_name_da='',cu_sub_name_da='' WHERE cu_iso_3='ZMW';
UPDATE static_currencies SET cu_name_da='Zimbabwisk dollar',cu_sub_name_da='' WHERE cu_iso_3='ZWD';
UPDATE static_currencies SET cu_name_da='',cu_sub_name_da='' WHERE cu_iso_3='AFN';
UPDATE static_currencies SET cu_name_da='',cu_sub_name_da='' WHERE cu_iso_3='RSD';
UPDATE static_currencies SET cu_name_da='Madagaskisk ariary',cu_sub_name_da='' WHERE cu_iso_3='MGA';
UPDATE static_currencies SET cu_name_da='',cu_sub_name_da='' WHERE cu_iso_3='SRD';
UPDATE static_currencies SET cu_name_da='Ny tyrkisk lira',cu_sub_name_da='' WHERE cu_iso_3='TRY';
UPDATE static_currencies SET cu_name_da='',cu_sub_name_da='' WHERE cu_iso_3='SSP';
UPDATE static_currencies SET cu_name_da='',cu_sub_name_da='' WHERE cu_iso_3='GHS';
UPDATE static_currencies SET cu_name_da='',cu_sub_name_da='' WHERE cu_iso_3='MZN';
UPDATE static_currencies SET cu_name_da='',cu_sub_name_da='' WHERE cu_iso_3='RON';
UPDATE static_currencies SET cu_name_da='',cu_sub_name_da='' WHERE cu_iso_3='TMT';

## static_languages

UPDATE static_languages SET lg_name_da='Abkhasisk' WHERE lg_iso_2='AB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Afar' WHERE lg_iso_2='AA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Afrikaans' WHERE lg_iso_2='AF' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Albansk' WHERE lg_iso_2='SQ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Amharisk' WHERE lg_iso_2='AM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Arabisk' WHERE lg_iso_2='AR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Armensk' WHERE lg_iso_2='HY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Assamesisk' WHERE lg_iso_2='AS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Aymara' WHERE lg_iso_2='AY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Aserbajdsjan' WHERE lg_iso_2='AZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Bashkir' WHERE lg_iso_2='BA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Baskisk' WHERE lg_iso_2='EU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Bengalsk' WHERE lg_iso_2='BN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Dzongkha' WHERE lg_iso_2='DZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Bihari' WHERE lg_iso_2='BH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Bislama' WHERE lg_iso_2='BI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Bretonsk' WHERE lg_iso_2='BR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Bulgarsk' WHERE lg_iso_2='BG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Burmesisk' WHERE lg_iso_2='MY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Hviderussisk' WHERE lg_iso_2='BE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Khmer' WHERE lg_iso_2='KM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Katalansk' WHERE lg_iso_2='CA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Zhuang' WHERE lg_iso_2='ZA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Kinesisk' WHERE lg_iso_2='ZH' AND lg_country_iso_2='HK';
UPDATE static_languages SET lg_name_da='Korsikansk' WHERE lg_iso_2='CO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Kroatisk' WHERE lg_iso_2='HR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Tjekkisk' WHERE lg_iso_2='CS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Dansk' WHERE lg_iso_2='DA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Hollandsk' WHERE lg_iso_2='NL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Engelsk' WHERE lg_iso_2='EN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Esperanto' WHERE lg_iso_2='EO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Estisk' WHERE lg_iso_2='ET' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Færøsk' WHERE lg_iso_2='FO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Persisk' WHERE lg_iso_2='FA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Fijian' WHERE lg_iso_2='FJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Finsk' WHERE lg_iso_2='FI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Fransk' WHERE lg_iso_2='FR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Frisisk' WHERE lg_iso_2='FY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Galicisk' WHERE lg_iso_2='GL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Gælisk (skotsk)' WHERE lg_iso_2='GD' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Manx' WHERE lg_iso_2='GV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Georgisk' WHERE lg_iso_2='KA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Tysk' WHERE lg_iso_2='DE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Græsk' WHERE lg_iso_2='EL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Kalaallisut' WHERE lg_iso_2='KL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Guarani' WHERE lg_iso_2='GN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Gujaratisk' WHERE lg_iso_2='GU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Hausa' WHERE lg_iso_2='HA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Hebraisk' WHERE lg_iso_2='HE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Hindi' WHERE lg_iso_2='HI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Ungarsk' WHERE lg_iso_2='HU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Islandsk' WHERE lg_iso_2='IS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Indonesisk' WHERE lg_iso_2='ID' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Interlingua' WHERE lg_iso_2='IA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Interlingue' WHERE lg_iso_2='IE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Inuktitut' WHERE lg_iso_2='IU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Inupiaq' WHERE lg_iso_2='IK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Irsk' WHERE lg_iso_2='GA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Italiensk' WHERE lg_iso_2='IT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Japansk' WHERE lg_iso_2='JA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Kannaresisk' WHERE lg_iso_2='KN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Kashmiri' WHERE lg_iso_2='KS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Kasakhisk' WHERE lg_iso_2='KK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Kinyarwanda' WHERE lg_iso_2='RW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Kirgisisk' WHERE lg_iso_2='KY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Rundi' WHERE lg_iso_2='RN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Koreansk' WHERE lg_iso_2='KO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Kurdisk' WHERE lg_iso_2='KU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Lao' WHERE lg_iso_2='LO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Latin' WHERE lg_iso_2='LA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Lettisk' WHERE lg_iso_2='LV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Lingala' WHERE lg_iso_2='LN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Litauisk' WHERE lg_iso_2='LT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Makedonsk' WHERE lg_iso_2='MK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Malagasy' WHERE lg_iso_2='MG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Malay' WHERE lg_iso_2='MS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Malayalam' WHERE lg_iso_2='ML' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Maltesisk' WHERE lg_iso_2='MT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Maori' WHERE lg_iso_2='MI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Marathisk' WHERE lg_iso_2='MR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Moldovisk' WHERE lg_iso_2='MO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Mongolsk' WHERE lg_iso_2='MN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Nauru' WHERE lg_iso_2='NA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Nepalesisk' WHERE lg_iso_2='NE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Norsk' WHERE lg_iso_2='NO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Occitansk (efter 1500); Proven' WHERE lg_iso_2='OC' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Oriya' WHERE lg_iso_2='OR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Oromo' WHERE lg_iso_2='OM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Pashto (Pushto)' WHERE lg_iso_2='PS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Polsk' WHERE lg_iso_2='PL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Portugisisk' WHERE lg_iso_2='PT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Punjabi' WHERE lg_iso_2='PA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Quechua' WHERE lg_iso_2='QU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Rætoromansk' WHERE lg_iso_2='RM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Rumænsk' WHERE lg_iso_2='RO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Russisk' WHERE lg_iso_2='RU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Samoansk' WHERE lg_iso_2='SM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Sango' WHERE lg_iso_2='SG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Sanskrit' WHERE lg_iso_2='SA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Serbisk' WHERE lg_iso_2='SR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Sotho, Southern' WHERE lg_iso_2='ST' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Tswana' WHERE lg_iso_2='TN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Shona' WHERE lg_iso_2='SN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Sindhi' WHERE lg_iso_2='SD' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Singalesisk' WHERE lg_iso_2='SI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Swati' WHERE lg_iso_2='SS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Slovakisk' WHERE lg_iso_2='SK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Slovensk' WHERE lg_iso_2='SL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Somalisk' WHERE lg_iso_2='SO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Spansk' WHERE lg_iso_2='ES' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Sundanesisk' WHERE lg_iso_2='SU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Swahili' WHERE lg_iso_2='SW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Svensk' WHERE lg_iso_2='SV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Tagalog' WHERE lg_iso_2='TL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Tajik' WHERE lg_iso_2='TG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Tamilsk' WHERE lg_iso_2='TA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Tatarisk' WHERE lg_iso_2='TT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Telugu' WHERE lg_iso_2='TE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Thailandsk' WHERE lg_iso_2='TH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Tibetansk' WHERE lg_iso_2='BO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Tigrinya' WHERE lg_iso_2='TI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Tonga (Tongaøerne)' WHERE lg_iso_2='TO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Tsonga' WHERE lg_iso_2='TS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Tyrkisk' WHERE lg_iso_2='TR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Turkmensk' WHERE lg_iso_2='TK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Twi' WHERE lg_iso_2='TW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Uigurisk' WHERE lg_iso_2='UG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Ukrainsk' WHERE lg_iso_2='UK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Urdu' WHERE lg_iso_2='UR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Usbekisk' WHERE lg_iso_2='UZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Vietnamesisk' WHERE lg_iso_2='VI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Volapük' WHERE lg_iso_2='VO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Walisisk' WHERE lg_iso_2='CY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Wolof' WHERE lg_iso_2='WO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Xhosa' WHERE lg_iso_2='XH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Jiddisch' WHERE lg_iso_2='YI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Yoruba' WHERE lg_iso_2='YO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Zulu' WHERE lg_iso_2='ZU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Bosnisk' WHERE lg_iso_2='BS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Avestan' WHERE lg_iso_2='AE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Akan' WHERE lg_iso_2='AK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Aragonesisk' WHERE lg_iso_2='AN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Avarisk' WHERE lg_iso_2='AV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Bambara' WHERE lg_iso_2='BM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Tjetjensk' WHERE lg_iso_2='CE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Chamorro' WHERE lg_iso_2='CH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Cree' WHERE lg_iso_2='CR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Kirkeslavisk' WHERE lg_iso_2='CU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Chuvash' WHERE lg_iso_2='CV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Divehi' WHERE lg_iso_2='DV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Ewe' WHERE lg_iso_2='EE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Fulah' WHERE lg_iso_2='FF' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Hiri Motu' WHERE lg_iso_2='HO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Haitisk' WHERE lg_iso_2='HT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Herero' WHERE lg_iso_2='HZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Igbo' WHERE lg_iso_2='IG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Sichuan Yi' WHERE lg_iso_2='II' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Ido' WHERE lg_iso_2='IO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Javanesisk' WHERE lg_iso_2='JV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Kongo' WHERE lg_iso_2='KG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Kikuyu' WHERE lg_iso_2='KI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Kuanyama' WHERE lg_iso_2='KJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Kanuri' WHERE lg_iso_2='KR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='' WHERE lg_iso_2='KV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Cornisk' WHERE lg_iso_2='KW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Luxembourgsk' WHERE lg_iso_2='LB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Ganda' WHERE lg_iso_2='LG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Limburgsk' WHERE lg_iso_2='LI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Luba-Katanga' WHERE lg_iso_2='LU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Marshallese' WHERE lg_iso_2='MH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Norsk Bokmål' WHERE lg_iso_2='NB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Ndebele, Nord' WHERE lg_iso_2='ND' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Ndonga' WHERE lg_iso_2='NG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Nynorsk' WHERE lg_iso_2='NN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Ndebele, Syd' WHERE lg_iso_2='NR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Navajo' WHERE lg_iso_2='NV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Nyanja; Chichewa; Chewa' WHERE lg_iso_2='NY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Ojibwa' WHERE lg_iso_2='OJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Ossetisk' WHERE lg_iso_2='OS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Pali' WHERE lg_iso_2='PI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Sardinsk' WHERE lg_iso_2='SC' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Nordsamisk' WHERE lg_iso_2='SE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Tahitiansk' WHERE lg_iso_2='TY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Venda' WHERE lg_iso_2='VE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Vallonsk' WHERE lg_iso_2='WA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_da='Portugisisk' WHERE lg_iso_2='PT' AND lg_country_iso_2='BR';
UPDATE static_languages SET lg_name_da='Kinesisk' WHERE lg_iso_2='ZH' AND lg_country_iso_2='CN';
UPDATE static_languages SET lg_name_da='' WHERE lg_iso_2='FR' AND lg_country_iso_2='CA';
UPDATE static_languages SET lg_name_da='' WHERE lg_iso_2='TL' AND lg_country_iso_2='PH';
UPDATE static_languages SET lg_name_da='' WHERE lg_iso_2='SR' AND lg_country_iso_2='ME';

## static_territories

UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='2';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='9';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='19';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='142';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='150';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='30';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='35';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='143';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='145';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='39';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='151';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='154';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='155';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='5';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='13';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='21';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='29';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='11';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='14';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='15';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='17';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='18';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='53';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='54';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='57';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='61';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='34';
UPDATE static_territories SET tr_name_da='' WHERE tr_iso_nr='419';